core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('predict/', include(('predict.urls', 'predict'), namespace='predict')),
    # path('arima', views.arima_views)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.new, name="new"),
    path('result/<str:id>', views.result, name='result'),
    path('arima/<str:id>', views.arima, name='arima'),
]

predict/models.py
from django.db import models

# Create your models here.
class predict(models.Model):
    file            = models.CharField(max_length=225, blank=True, null=True)
    created         = models.DateField(auto_now_add=True)
    windows_size    = models.IntegerField(default=24)
    epochs          = models.IntegerField(default=50)
    batch_size      = models.IntegerField(default=400)
    rmse_predict    = models.IntegerField(default=0)
    mae_predict     = models.IntegerField(default=0)
    mape_predict    = models.IntegerField(default=0)
    mase_predict    = models.IntegerField(default=0)
    mse_arima       = models.IntegerField(default=0)
    rmse_arima      = models.IntegerField(default=0)
    mae_arima       = models.IntegerField(default=0)
    mape_arima      = models.IntegerField(default=0)
    mase_arima      = models.IntegerField(default=0)

core/views.py
from django.shortcuts import render, redirect
from predict.models import predict as Predict

from .utils import predict,  load_csv, arima


def index(request):
    context = {
        'history':Predict.objects.all()
    }

    return render(request, 'index.html', context)

def arima_views(request, id):
    # if request.method == 'POST':
    df, df_day, df_hour = load_csv('media/main.csv')
    mse, rmse, mae, mape, mase = arima(df_hour)
    context = {
        'mse':mse,
        'rmse':rmse,
        'mae':mae,
        'mape':mape,
        'mase':mase
    }
    return render(request, 'arima.html', context)

predict/views.py
from django.shortcuts import render, redirect
from .models import predict as Predict
from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
from core.utils import predict,  load_csv, arima

# Create your views here.
def new(request):
    context = {}
    if request.method == 'POST':
        windows_size = request.POST['windows_size'] #24
        epochs = request.POST['epochs']             #50
        batch_size = request.POST['batch_size']      #400
        file = request.FILES['file']
        predict_result = Predict.objects.create(windows_size=windows_size, epochs=epochs, batch_size=batch_size)
        
        fs = FileSystemStorage()
        fs.save(str(predict_result.id)+'/main.csv', file)
        rmse, mae, mape, mase, mse_arima, rmse_arima, mae_arima, mape_arima, mase_arima = predict(file, int(windows_size), int(epochs), int(batch_size), predict_result.id)

        predict_result.rmse_predict = rmse
        predict_result.mae_predict = mae
        predict_result.mape_predict = mape
        predict_result.mase_predict = mase
        predict_result.mse_arima = mse_arima
        predict_result.rmse_arima = rmse_arima
        predict_result.mae_arima = mae_arima
        predict_result.mape_arima = mape_arima
        predict_result.mase_arima = mase_arima
        predict_result.save()
        return redirect('predict:result', id=predict_result.id)
    return render(request, 'new.html', context)

def result(request, id):
    context = {
        'predict':Predict.objects.get(id=id)
    }
    return render(request, 'result.html', context)

def arima(request, id):
    df, df_day, df_hour = load_csv('media/'+ str(id) +'/main.csv')
    mse, rmse, mae, mape, mase = arima(df_hour, id=id)
    Predict.objects.filter(id=id).update(mse_arima=mse , rmse_arima= rmse, mae_arima= mae, mape_arima= mape, mase_arima=mase)
    return redirect('predict:result', id=id)

templates/arima.html
{% extend 'base.html' %}
{% block main %}
<div class="container mt-5">
    {% if mse %}
    <div class="row">
        <div class="col-md-5">
            <div class="my-4 p-5">
                <div class="h5 text-uppercase">mse : {{mse}} <br></div>
                <div class="h5 text-uppercase">rmse : {{rmse}} <br></div>
                <div class="h5 text-uppercase">mae : {{mae}} <br></div>
                <div class="h5 text-uppercase">mape : {{mape}} <br></div>
                <div class="h5 text-uppercase">mase : {{mase}} <br></div>
            </div>
        </div>
        <div class="col-md-7">
            <img src="/media/arima.png" width="100%" alt="">
        </div>
        <div class="col-12">
            <img src="/media/arima_predict.png" width="100%" alt="">
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LSTM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg text-white bg-light shadow-sm fixed-top">
        <div class="container">
          <a class="navbar-brand" href="#">LSTM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% block navbar %}
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0"></ul>
            {% endblock %}
            <div class="d-flex gap-2">
              <a href="{% url 'predict:new' %}" class="btn btn-primary align-self-center">History</a>
              <a href="{% url 'predict:new' %}" class="btn btn-outline-primary align-self-center">Upload</a>
            </div>
          </div>
        </div>
      </nav>
      <br><br><br>
      {% block content %} {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/history.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg text-white bg-primary">
        <div class="container">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Upload File</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container mt-5">
        {% if mse %}
        <div class="row">
            <div class="col-md-5">
                <div class="my-4 p-5">
                    <div class="h5 text-uppercase">mse : {{mse}} <br></div>
                    <div class="h5 text-uppercase">rmse : {{rmse}} <br></div>
                    <div class="h5 text-uppercase">mae : {{mae}} <br></div>
                    <div class="h5 text-uppercase">mape : {{mape}} <br></div>
                    <div class="h5 text-uppercase">mase : {{mase}} <br></div>
                </div>
            </div>
            <div class="col-md-7">
                <img src="/media/arima.png" width="100%" alt="">
            </div>
            <div class="col-12">
                <img src="/media/arima_predict.png" width="100%" alt="">
            </div>
        </div>
        {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    {% for predict in predict %}
    <div class="bg-white shadow p-3 d-flex gap-2 my-2">
        <h5 class="align-self-center col">Percobaan {{predict.id}}</h5>
        <a href="{% url 'predict:result' id=predict.id %}" class="btn btn-primary align-self-center">Result</a>
    </div>
    <a href="{% url 'predict:new' %}" class="btn btn-primary">Buat Baru</a>
    {% endfor %}
</div>
{% endblock content %}

templates/new.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="csf_file" class="form-label">Upload CSV File</label>
            <input class="form-control" name="file" type="file" id="csf_file">
        </div>
        <div class="mb-3">
            <label for="windows_size" class="form-label">Windows Size</label>
            <input type="number" class="form-control" name="windows_size" id="windows_size" placeholder="Input Windows Size" value="24">
        </div>
        <div class="mb-3">
            <label for="epochs" class="form-label">Epochs</label>
            <input type="number" class="form-control" name="epochs" id="epochs" placeholder="Input epochs" value="50">
        </div>
        <div class="mb-3">
            <label for="batch_size" class="form-label">Batch size</label>
            <input type="number" class="form-control" name="batch_size" id="batch_size" placeholder="Input Batch size" value="4000">
        </div>
        <button type="submit" class="btn btn-primary">Process</button>
    </form>
</div>
{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="navbar-nav mx-auto mb-2 mb-lg-0">
    <li class="nav-item"> <a class="nav-link active" aria-current="page" href="#training">Training</a></li>
    <li class="nav-item"><a class="nav-link" href="#arima">Arima</a></li>
    <li class="nav-item"><a class="nav-link" href="#analisis">Explore</a></li>
    <li class="nav-item"><a class="nav-link" href="#prediksi">Prediksi Power</a></li>
    <li class="nav-item"><a class="nav-link" href="#result">Keseluruhan</a></li>
  </ul>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="display-5 mt-5" id="training">Training </div>
    <div class="m-2 p-3 rounded-3 shadow bg-white row">
        <div class="d-flex flex-column gap-2 col-md-6">
            <div class="text-uppercase"><p class="m-3 p-3 shadow">rmse : {{predict.rmse_predict}}</p></div>
            <div class="text-uppercase"><p class="m-3 p-3 shadow">mae : {{predict.mae_predict}}</p></div>
            <div class="text-uppercase"><p class="m-3 p-3 shadow">mape : {{predict.mape_predict}}</p></div>
            <div class="text-uppercase"><p class="m-3 p-3 shadow">mase : {{predict.mase_predict}}</p></div>
        </div>
        <div class="text-center col-md-6"><img src="/media/{{predict.id}}/power.png" height="100%" alt=""></div>
        <img class="col-12" src="/media/{{predict.id}}/Data_Histori.png" width="100%" alt="">
    </div>

    <div class="display-5 mt-5" id="arima">Algoritma Arima</div>
    <div class="row">
        <div class="col text-uppercase bg-white"><p class="m-1 p-3 shadow">mse : {{predict.mse_arima}}</p></div>
        <div class="col text-uppercase bg-white"><p class="m-1 p-3 shadow">rmse : {{predict.rmse_arima}}</p></div>
        <div class="col text-uppercase bg-white"><p class="m-1 p-3 shadow">mae : {{predict.mae_arima}}</p></div>
        <div class="col text-uppercase bg-white"><p class="m-1 p-3 shadow">mape : {{predict.mape_arima}}</p></div>
        <div class="col text-uppercase bg-white"><p class="m-1 p-3 shadow">mase : {{predict.mase_arima}}</p></div>
    </div>
    <div class="m-2 p-3 rounded-3 shadow bg-white">
        <h4>Train Test</h4>
        <div class="text-center"><img src="/media/{{predict.id}}/arima_predict.png" width="100%" alt=""></div>
        <h4>Actual</h4>
        <img src="/media/{{predict.id}}/arima.png" width="100%" alt="">
    </div>

    <div class="display-5 mt-5" id="analisis">EXPLORATORY DATA ANALYSIS</div>
    <div class=" bg-white shadow rounded-3 p-3">
        <h4>Histogram</h4><div class="text-center my-1"><img class="w-50" src="/media/{{predict.id}}/data_analyst.png" alt=""></div>
        <h4>Pola Harian</h4><div class="text-center my-1"><img class="w-75" src="/media/{{predict.id}}/pola_harian.png" alt=""></div>
    </div>

    <div class="display-5 mt-5" id="prediksi">Prediksi Power</div>
    <div class=" bg-white shadow rounded-3 p-3">
        <h4>Prediksi Penggunaan</h4>
        <div class="text-center my-1">
            <img class="w-75" src="/media/{{predict.id}}/prediksi_penggunaan.png" alt="">
            <img class="w-75" src="/media/{{predict.id}}/penggunaan_harian.png" alt="">
            <img class="w-75" src="/media/{{predict.id}}/pola_harian.png" alt="">
        </div>
    </div>

    <div class="display-5 mt-5" id="result">Keseluruhan</div>
    <div class=" bg-white shadow rounded-3 p-3">
        <div class="text-center my-1">
            <img class="w-75" src="/media/{{predict.id}}/resume.png" alt="">
            <img class="w-75" src="/media/{{predict.id}}/resampling.png" alt="">
        </div>
        <div class="text-center my-1">
            <img style="width: 100%; height: 300px; object-fit: cover; object-position: -20% 0;" src="/media/{{predict.id}}/freq.png" alt="">
            <img style="width: 100%; height: 300px; object-fit: cover; object-position: -20% 0;" src="/media/{{predict.id}}/chart.png" alt="">
        </div>
    </div>

</div>
{% endblock %}